Upgrade to .Net Core 3.0.
MichalJankowskii/Moq.EntityFrameworkCore pull request #8
Opened 2019-09-24 19:30 UTC by cbehrends

DbQuery has been deprecated so I've moved he impl over to DbSet.

2019-09-29 08:03 UTC, MichalJankowskii reviewed
I am not able to accept your changes because:
- added some custom unit tests
- removed support for DbQuery - it should be marked as Obsolete
- the main project should be targeted to netstandard 2.1

I created commit based on your changes with mentioned fixes already.

2019-09-29 11:44 UTC, cbehrends commented
Glad the code was of use. 

I should warn you however that I've encountered some anomalies in relation to collections which forced me to stop using this library.  I was in a hurry at the time and had to get some code out, so I unfortunately did not write a test for it.  If I get some time I'll try to re-create it, if I can I'll write just the test and submit a PR.

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs
> +        [Fact]
What for is that test?

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Examples/Moq.EntityFrameworkCore.Examples.csproj
> +    <PackageReference Include="Moq" Version="4.13.0" />
Moq version update is not needed.

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Examples/Users/UsersContext.cs
> -        public virtual DbQuery<Role> Roles { get; set; }
Deprecated - does not mean deletesd. Still, support should be in the package. Only Obsolete attribute should be added.

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Examples/Users/UsersService.cs
> +﻿using System.Threading;
Using should be in namespace

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Examples/Users/UsersService.cs
> +        public async Task<User> GetOne(int userId)
What is the purpose of this method?

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Tests/Moq.EntityFrameworkCore.Tests.csproj
> +    <PackageReference Include="Moq" Version="4.13.0" />
There is no need for new Moq package

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore.Tests/DbAsyncQueryProvider/InMemoryAsyncQueryProviderTests.cs
> +            this.queryProviderMock.Verify(x => x.Execute<object>(this.expression));
<object> is not needed

2019-10-06 21:12 UTC, MichalJankowskii commented on src/Moq.EntityFrameworkCore/DbAsyncQueryProvider/InMemoryAsyncEnumerable.cs
> +﻿using System.Threading;
Using in namespace

2019-10-06 21:14 UTC, MichalJankowskii requested changes
I added comments for the future.

Lib is already supporting EF3.0

2019-10-12 19:56 UTC, closed without merging